const pt = {
  about:'Sobre', how:'Como funciona', eyebrow:'SEU GOSTO ESTÁ EM JULGAMENTO', hero:'Todo mundo é crítico.', punch:'Até ser criticado.', sub:'Anos de escolhas cinematográficas. Uma IA sem muita delicadeza. Seu diário tem coisas a explicar.', drop:'Arraste seu export para cá', choose:'Escolher arquivo .zip', limit:'ZIP do Letterboxd · até 50 MB', judge:'Julgar meu Letterboxd', demo:'Só quero ver uma demonstração ↗', privacy:'Seu export é usado para gerar o julgamento.', exportHelp:'Como consigo meu export?', instructions:'No Letterboxd, abra Settings → Import & Export → Export your data. Baixe o ZIP e escolha o arquivo aqui.', aboutText:'Uma pequena sessão de cinema sobre suas decisões. O Judge apresenta os dados, encontra os contrastes e dá seu veredito. Você só precisa assistir.', footer:'SEM NOTAS PARA A SUA PESSOA. SÓ PARA O SEU GOSTO.', remove:'Remover', analyzing:'Um instante. Estou acomodando o seu ego.', loading:'Abrindo o export…|Lendo suas decisões…|Aguardando o veredito…', loadingNote:'O ZIP é analisado pela aplicação web. O julgamento começa quando o roteiro chegar.', back:'Voltar', pause:'Pausar', resume:'Continuar', skip:'Pular animações', restart:'Recomeçar', controls:'Controles', bottom:'↓ Voltar ao julgamento', typing:'Judge está digitando', favorites:'OS FAVORITOS. AS EVIDÊNCIAS.', evidence:'EVIDÊNCIA', done:'Sobreviveu.', another:'Julgar outro export', replay:'Rever desde o início', all:'Mostrar tudo sem animação', share:'Compartilhar resultado', shared:'Resultado copiado.', download:'Baixar resultado em texto', demoLabel:'DEMONSTRAÇÃO · ROTEIRO REAL', noRating:'Sem nota', more:'Ler descrição', errorTitle:'Corta. Algo saiu do roteiro.', zip:'Escolha um arquivo ZIP válido.', large:'Esse arquivo ultrapassa o limite de 50 MB.', exportFormat:'Esse ZIP não parece ser um export oficial do Letterboxd.', emptyExport:'Não encontrei filmes nesse export.', configuration:'O Judge web ainda não tem uma chave Gemini configurada no Cloudflare.', offline:'Não consegui alcançar o Judge. Confira sua conexão e tente novamente.', timeout:'O Judge demorou demais. Tente novamente.', unavailable:'O Judge web não está disponível nesta publicação.', rate:'Muitos julgamentos ao mesmo tempo. Tente novamente mais tarde.', server:'O Judge teve um problema. Tente novamente em instantes.', invalid:'A resposta não contém um roteiro válido.', incompatible:'Esta versão do roteiro ainda não é compatível.', retry:'Tentar novamente', demoAction:'Testar demo', session:'SESSÃO DE JULGAMENTO', shareTitle:'Meu julgamento cinematográfico', posterCredit:'Pôsteres: TMDB. Este produto não é endossado nem certificado pelo TMDB.'
};
const en = {
  about:'About', how:'How it works', eyebrow:'YOUR TASTE IS ON TRIAL', hero:'Everyone is a critic.', punch:'Until it gets personal.', sub:'Years of questionable movie choices. One AI with very little tact. Your diary has some explaining to do.', drop:'Drop your export here', choose:'Choose a .zip file', limit:'Letterboxd ZIP · up to 50 MB', judge:'Judge my Letterboxd', demo:'Just show me a demonstration ↗', privacy:'Your export is used to generate the judgment.', exportHelp:'Where do I get my export?', instructions:'On Letterboxd, open Settings → Import & Export → Export your data. Download the ZIP and select it here.', aboutText:'A small screening of your decisions. The Judge presents the evidence, spots the contrasts and delivers a verdict. You just watch.', footer:'JUDGING YOUR TASTE. NOT YOUR WORTH.', remove:'Remove', analyzing:'One moment. Making room for your ego.', loading:'Opening the export…|Reading your decisions…|Waiting for the verdict…', loadingNote:'The ZIP is analyzed by the web application. The judgment starts when the script arrives.', back:'Back', pause:'Pause', resume:'Resume', skip:'Skip animations', restart:'Restart', controls:'Controls', bottom:'↓ Back to the judgment', typing:'Judge is typing', favorites:'THE FAVORITES. THE EVIDENCE.', evidence:'EVIDENCE', done:'You survived.', another:'Judge another export', replay:'Watch from the start', all:'Show everything without animation', share:'Share result', shared:'Result copied.', download:'Download text result', demoLabel:'DEMO · REAL SCRIPT', noRating:'Not rated', more:'Read description', errorTitle:'Cut. Something went off script.', zip:'Choose a valid ZIP file.', large:'This file exceeds the 50 MB limit.', exportFormat:'This ZIP does not look like an official Letterboxd export.', emptyExport:'I could not find any films in this export.', configuration:'The web Judge does not have a Gemini key configured in Cloudflare yet.', offline:'Could not reach the Judge. Check your connection and try again.', timeout:'The Judge took too long. Try again.', unavailable:'The web Judge is unavailable in this deployment.', rate:'Too many judgments right now. Please try again later.', server:'The Judge ran into a problem. Try again shortly.', invalid:'The response does not contain a valid script.', incompatible:'This script version is not supported yet.', retry:'Try again', demoAction:'Try demo', session:'JUDGMENT IN SESSION', shareTitle:'My movie judgment', posterCredit:'Posters: TMDB. This product is not endorsed or certified by TMDB.'
};
export let locale = navigator.language.startsWith('pt') ? 'pt-BR' : 'en-US';
export const t = key => (locale === 'pt-BR' ? pt : en)[key] || key;
export function setLocale(value) {
  locale = value === 'pt-BR' ? value : 'en-US'; document.documentElement.lang = locale;
  document.querySelectorAll('[data-i18n]').forEach(n => { n.textContent = t(n.dataset.i18n); });
}
