const SIZES={post:{width:1080,height:1350},story:{width:1080,height:1920}};
const wrap=(ctx,value,width)=>{const lines=[];let line='';for(const word of String(value||'').split(/\s+/)){const next=(line+' '+word).trim();if(line&&ctx.measureText(next).width>width){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);return lines;};
const text=(ctx,value,x,y,width,lineHeight,max)=>{let row=y;for(const line of wrap(ctx,value,width).slice(0,max)){ctx.fillText(line,x,row);row+=lineHeight;}return row;};
const fittedText=(ctx,value,{x,y,width,maxHeight,maximum,minimum})=>{for(let size=maximum;size>=minimum;size-=2){ctx.font=`${size}px Georgia`;const lineHeight=Math.round(size*1.28),lines=wrap(ctx,value,width);if(lines.length*lineHeight<=maxHeight){text(ctx,value,x,y,width,lineHeight,lines.length);return {size,lineHeight,lines:lines.length};}}ctx.font=`${minimum}px Georgia`;const lineHeight=Math.round(minimum*1.28),lines=wrap(ctx,value,width);text(ctx,value,x,y,width,lineHeight,lines.length);return {size:minimum,lineHeight,lines:lines.length};};
const load=url=>new Promise(resolve=>{if(!url)return resolve(null);const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=url;});
const common=(format,handle)=>{const size=SIZES[format]||SIZES.post,canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d');ctx.fillStyle='#101619';ctx.fillRect(0,0,size.width,size.height);ctx.fillStyle='#caff83';ctx.fillRect(0,0,size.width,12);ctx.fillStyle='#caff83';ctx.font='24px monospace';ctx.fillText('JUDGE MY LETTERBOXD',72,format==='story'?110:86);ctx.fillStyle='#eef3ed';ctx.font='32px Arial';ctx.fillText('@'+(handle||'letterboxd'),72,format==='story'?180:150);ctx.beginPath();for(const x of [990,1015,1040])ctx.arc(x,format==='story'?105:80,8,0,Math.PI*2);ctx.fill();return {canvas,ctx};};
export async function makeShareCards(script,{posterUrls=[],format='post'}={}){
 const story=format==='story',films=script.opening?.top_four||[],posters=await Promise.all(posterUrls.slice(0,4).map(url=>load(url?'/api/image-proxy?url='+encodeURIComponent(url):'')));
 const archetypeValid=script.opening?.top_four_archetype?.valid===true&&Boolean(script.opening?.archetype_text),archetype=archetypeValid?common(format,script.profile?.handle):null,phrase=script.opening?.archetype_text||'',posterY=story?1050:820,posterWidth=story?216:202,posterHeight=story?324:300,gap=story?232:234;
 if(archetype){
 archetype.ctx.fillStyle='#eef3ed';archetype.ctx.font='30px Arial';archetype.ctx.fillText('VOCÊ DEVE SER O...',72,story?270:255);archetype.ctx.fillStyle='#caff83';archetype.ctx.font=`bold ${story?88:78}px Georgia`;text(archetype.ctx,phrase,72,story?360:350,900,story?100:88,story?7:6);
 films.slice(0,4).forEach((film,index)=>{const x=72+index*gap,y=posterY;archetype.ctx.fillStyle=['#354749','#6c513c','#4f5f3f','#485675'][index];archetype.ctx.fillRect(x,y,posterWidth,posterHeight);if(posters[index])archetype.ctx.drawImage(posters[index],x,y,posterWidth,posterHeight);else{archetype.ctx.fillStyle='#eef3ed';archetype.ctx.font='bold 22px Georgia';text(archetype.ctx,film.title,x+14,y+posterHeight-75,posterWidth-28,27,3);}});
 archetype.ctx.fillStyle='#9fa9a4';archetype.ctx.font='22px Arial';archetype.ctx.fillText('Pode ser só @'+(script.profile?.handle||'você')+'.',72,story?1745:1235);
 }
 const review=common(format,script.profile?.handle),profile=script.profile_review||{};review.ctx.fillStyle='#9fa9a4';review.ctx.font='28px Arial';review.ctx.fillText('SE EU FOSSE FALAR DE VOCÊ COMO VOCÊ FALA DOS FILMES...',72,story?330:255);review.ctx.fillStyle='#eef3ed';fittedText(review.ctx,profile.text||'O julgamento acabou antes desta review.',{x:72,y:story?470:350,width:900,maxHeight:story?1180:850,maximum:story?56:48,minimum:story?34:30});
 return {...(archetype?{archetype:archetype.canvas}:{}),profile_review:review.canvas};
}
export const cardBlob=canvas=>new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
export function downloadCard(canvas,name){canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');}
