const size={width:1080,height:1350};
const wrap=(ctx,text,width)=>{const words=String(text||'').split(/\s+/),lines=[];let line='';for(const word of words){const next=(line+' '+word).trim();if(ctx.measureText(next).width>width&&line){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);return lines;};
const load=url=>new Promise(resolve=>{if(!url)return resolve(null);const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=url;});
const avatar=(ctx,handle,x,y,image)=>{ctx.save();ctx.beginPath();ctx.arc(x,y,58,0,Math.PI*2);ctx.clip();if(image)ctx.drawImage(image,x-58,y-58,116,116);else{ctx.fillStyle='#caff83';ctx.fillRect(x-58,y-58,116,116);ctx.fillStyle='#142019';ctx.font='bold 46px Arial';ctx.textAlign='center';ctx.fillText((handle||'?').slice(0,2).toUpperCase(),x,y+16);}ctx.restore();};
const text=(ctx,value,x,y,width,lineHeight,max=9)=>{let row=y;for(const line of wrap(ctx,value,width).slice(0,max)){ctx.fillText(line,x,row);row+=lineHeight;}return row;};
export async function makeShareCards(script,{avatarUrl='',posterUrls=[]}={}){
 const avatarImage=await load(avatarUrl);
 const common=kind=>{const canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d');ctx.fillStyle='#101619';ctx.fillRect(0,0,size.width,size.height);ctx.fillStyle='#caff83';ctx.fillRect(0,0,size.width,12);ctx.fillStyle='#caff83';ctx.font='24px monospace';ctx.textAlign='left';ctx.fillText('JUDGE MY LETTERBOXD',72,86);avatar(ctx,script.profile?.handle,930,80,avatarImage);ctx.fillStyle='#eef3ed';ctx.font='32px Arial';ctx.fillText('@'+(script.profile?.handle||'letterboxd'),72,150);return {canvas,ctx,kind};};
 const archetype=common('archetype'),phrase=script.opening?.archetype_text||'';
 archetype.ctx.fillStyle='#eef3ed';archetype.ctx.font='30px Arial';archetype.ctx.fillText('VOCÊ DEVE SER O...',72,255);archetype.ctx.fillStyle='#caff83';archetype.ctx.font='bold 78px Georgia';text(archetype.ctx,phrase||'UM CASO DIFÍCIL',72,350,900,88,6);
 const films=script.opening?.top_four||[],posters=await Promise.all(posterUrls.slice(0,4).map(url=>load(url?'/api/image-proxy?url='+encodeURIComponent(url):'')));films.slice(0,4).forEach((film,index)=>{const x=72+index*234,y=820;archetype.ctx.fillStyle=['#354749','#6c513c','#4f5f3f','#485675'][index];archetype.ctx.fillRect(x,y,202,300);if(posters[index])archetype.ctx.drawImage(posters[index],x,y,202,300);else{archetype.ctx.fillStyle='#eef3ed';archetype.ctx.font='bold 24px Georgia';text(archetype.ctx,film.title,x+15,y+220,172,28,3);archetype.ctx.font='18px monospace';archetype.ctx.fillText(film.year||'',x+15,y+278);}});
 archetype.ctx.fillStyle='#9fa9a4';archetype.ctx.font='22px Arial';archetype.ctx.fillText('Pode ser só @'+(script.profile?.handle||'você')+'.',72,1235);
 const review=common('profile_review'),profile=script.profile_review||{};
 review.ctx.fillStyle='#9fa9a4';review.ctx.font='28px Arial';review.ctx.fillText('SE EU FOSSE FALAR DE VOCÊ COMO VOCÊ FALA DOS FILMES...',72,255);review.ctx.fillStyle='#eef3ed';review.ctx.font='48px Georgia';text(review.ctx,profile.text||'O julgamento acabou antes desta review.',72,350,900,62,12);
 return {archetype:archetype.canvas,profile_review:review.canvas};
}
export const cardBlob=canvas=>new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
export function downloadCard(canvas,name){canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');}
