import {getPublicResult} from './_lib/public-results.js';
import React from 'react';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const parse=pathname=>{const match=decodeURI(pathname).match(/^\/@([^/]+)\/Judge-(\d+)(\/og\.png)?\/?$/i);return match?{profile:match[1],number:Number(match[2]),og:Boolean(match[3])}:null;};
const fallbackHtml=(status,title,body)=>new Response(`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="robots" content="noindex"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title><style>body{margin:0;background:#101619;color:#f4f1e8;font:18px system-ui;display:grid;place-items:center;min-height:100vh}main{text-align:center}a{color:#79dc9b}</style><main><h1>${esc(title)}</h1><p>${esc(body)}</p><a href="/">Judge My Letterboxd</a></main></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8'}});
const h=React.createElement;
export const ogImage=(row,result)=>{const films=(result.opening?.top_four||[]).slice(0,4),archetype=result.opening?.archetype_text||result.opening?.top_four_archetype?.phrase||'Perfil cinematográfico sob julgamento';while(films.length<4)films.push({title:'Sem pôster'});return h('div',{style:{width:'100%',height:'100%',display:'flex',flexDirection:'column',background:'#101619',color:'#f4f1e8',padding:'58px 64px',fontFamily:'sans-serif'}},
  h('div',{style:{display:'flex',alignItems:'center',fontSize:24,fontWeight:700,letterSpacing:1}},h('span',{style:{width:28,height:28,borderRadius:14,background:'#79dc9b',marginRight:16}}),'JUDGE MY LETTERBOXD'),
  h('div',{style:{display:'flex',marginTop:38,gap:18}},...films.map(film=>/^https:\/\//.test(film.poster_url||'')?h('img',{src:film.poster_url,width:165,height:248,style:{objectFit:'cover',borderRadius:10}}):h('div',{style:{width:165,height:248,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',padding:18,borderRadius:10,background:'linear-gradient(145deg,#31464a,#182128)',fontSize:18}},String(film.title||'Sem pôster').slice(0,42)))),
  h('div',{style:{display:'flex',alignItems:'flex-end',justifyContent:'space-between',marginTop:34}},h('div',{style:{display:'flex',flexDirection:'column'}},h('span',{style:{color:'#79dc9b',fontSize:25}},`@${row.profile_display}`),h('strong',{style:{fontSize:48,marginTop:6}},`JUDGE #${String(row.judge_number).padStart(2,'0')}`)),h('span',{style:{width:540,color:'#a9b1ad',fontSize:23,textAlign:'right'}},String(archetype).slice(0,90))));};
export async function onRequest({request,env}){
  const url=new URL(request.url),route=parse(url.pathname);if(!route)return fallbackHtml(404,'Página não encontrada','Esse caminho não existe.');
  const row=await getPublicResult(env?.RESULTS_DB,route.profile,route.number);if(!row)return fallbackHtml(404,'Julgamento não encontrado','Este resultado não existe ou não está mais disponível.');
  let result;try{result=JSON.parse(row.presentation_json);}catch{return fallbackHtml(500,'Resultado indisponível','Não foi possível reconstruir este julgamento.');}
  if(route.og){const render=env?.__TEST_OG_RENDERER||(async element=>{const {ImageResponse}=await import('@cloudflare/pages-plugin-vercel-og/api');return new ImageResponse(element,{width:1200,height:630});}),image=await render(ogImage(row,result));image.headers.set('Cache-Control','public, max-age=31536000, immutable');image.headers.set('X-Content-Type-Options','nosniff');return image;}
  const canonical=`${url.origin}/@${encodeURIComponent(row.profile_display)}/Judge-${String(row.judge_number).padStart(2,'0')}`,title=`@${row.profile_display} foi julgado — Judge #${String(row.judge_number).padStart(2,'0')}`,description=row.description,og=`${canonical}/og.png`,locale=row.locale||'pt-BR';
  const asset=await env.ASSETS.fetch(new URL('/index.html',url)),base=await asset.text(),meta=`<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="noindex,follow"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(og)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:url" content="${esc(canonical)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(og)}">`,html=base.replace(/<title>[\s\S]*?<\/title>/i,'').replace('</head>',`${meta}</head>`).replace('<body>',`<body><script id="public-result" type="application/json">${JSON.stringify(result).replace(/</g,'\\u003c')}</script>`).replace('<html lang="pt-BR">',`<html lang="${esc(locale)}">`);
  return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'public, max-age=60, s-maxage=300','X-Content-Type-Options':'nosniff'}});
}
