import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const base=process.env.WEB_BASE_URL||'http://127.0.0.1:8080',browser=await chromium.launch(),page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
await page.route('**/api/poster?*',route=>route.fulfill({json:{resolved:false}}));

await page.goto(base+'/web-tests/games.html?game=forced');await page.locator('.game-card').waitFor();assert.equal((await page.locator('.game-card').textContent()).includes('★'),false);const source=await page.locator('.triage-film').first().boundingBox(),target=await page.locator('.triage-role').first().boundingBox();await page.mouse.move(source.x+source.width/2,source.y+source.height/2);await page.mouse.down();await page.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:5});await page.mouse.up();assert.match(await page.locator('.triage-role').first().textContent(),/Film A/);for(let index=1;index<3;index++){await page.locator('.triage-film').first().click();await page.locator('.triage-role').nth(index).click();}await page.locator('.game-confirm').click();await page.locator('#done').filter({hasText:'PASS'}).waitFor();assert.match(await page.locator('.game-result').textContent(),/forced específica/);assert.match(await page.locator('#chat').textContent(),/TIMELINE_CONTINUED/);

await page.goto(base+'/web-tests/games.html?game=blind');await page.locator('.game-card').waitFor();assert.equal(await page.locator('select').count(),0);assert.equal(await page.locator('.rank-slot').count(),3);assert.equal((await page.locator('.game-card').textContent()).includes('★'),false);for(const rank of ['1','2','3']){await page.locator(`.rank-slot[data-rank="${rank}"]`).click();}await page.locator('#done').filter({hasText:'PASS'}).waitFor();assert.match(await page.locator('.game-result').textContent(),/Match histórico/);assert.match(await page.locator('.game-card').textContent(),/★/);

await page.goto(base+'/web-tests/games.html?game=defend');await page.locator('.game-card').waitFor();await page.locator('.game-choice-card').first().focus();assert.equal(await page.locator('.game-choice-card').first().evaluate(node=>node===document.activeElement),true);await page.keyboard.press('Enter');await page.locator('#done').filter({hasText:'PASS'}).waitFor();assert.match(await page.locator('#chat').textContent(),/TIMELINE_CONTINUED/);

await page.goto(base+'/web-tests/games.html?game=forced');await page.locator('.game-skip').click();await page.locator('#done').filter({hasText:'PASS'}).waitFor();assert.match(await page.locator('.game-result').textContent(),/pulado/);assert.match(await page.locator('#chat').textContent(),/TIMELINE_CONTINUED/);
await page.evaluate(async()=>{const {appendRich}=await import('/js/utils.js');const host=document.createElement('div');host.id='rich-profile-test';appendRich(host,{kind:'blockquote',runs:[{text:'<blockquote>citação segura</blockquote>',effect:'quote'}]},{profile:true});document.body.append(host);});
assert.equal(await page.locator('#rich-profile-test blockquote').count(),1);assert.equal((await page.locator('#rich-profile-test').textContent()).includes('<blockquote>'),false);
await browser.close();console.log('PASS: forced triage, blind rank, defend take, keyboard, hidden ratings, skip and timeline resume.');
