const clean=value=>String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,500),segments=text=>[{text:clean(text),effect:'none'}],message=(text,extra={})=>({type:'message',segments:segments(text),...extra}),typing=(duration='short')=>({type:'typing',duration}),pause=(duration='medium')=>({type:'pause',duration});
const firstObject=(archive,path)=>{const file=(archive.files||[]).find(row=>row.path.toLowerCase()===path);if(!file?.rows?.length)return {};const headers=file.headers||[],data=file.rows.slice(1).find(row=>row.cells?.some(Boolean));return data?Object.fromEntries(headers.map((header,index)=>[header,data.cells[index]??''])):{}};
const filmObject=film=>film?{film_id:film.film_id,film_key:film.film_id,title:film.title,year:film.year,rating:film.current_rating,uri:film.uri}:null;
const topFour=archive=>{const refs=String(firstObject(archive,'profile.csv')['Favorite Films']||'').split(',').map(v=>v.trim().replace(/\/$/,'')).filter(Boolean).slice(0,4),films=Object.values(archive.entities?.films||{});return refs.map(ref=>filmObject(films.find(f=>String(f.uri||'').replace(/\/$/,'')===ref))||{film_id:ref,film_key:ref,title:ref,year:null,rating:null});};
const attachmentEvent=(item,archive)=>{const entities=archive.entities||{},films=entities.films||{},resolve=id=>filmObject(films[id]);switch(item.type){case'film':return {type:'film',film:resolve(item.film_id)};case'film_pair':case'film_group':return {type:item.type,films:(item.film_ids||[]).map(resolve).filter(Boolean)};case'review_quote':{const review=entities.reviews?.[item.review_ref];return review?{type:'review_quote',film_key:review.film_id,title:review.title,year:review.year,rating:review.rating,text:review.text}:null;}case'tag':{const tag=entities.tags?.[item.tag_id];return {type:'tag',tag:tag?.name||item.tag||'',films:(tag?.film_ids||[]).slice(0,4).map(resolve).filter(Boolean),stats:[]};}case'list':{const list=entities.lists?.[item.list_id];return list?{type:'list',name:list.name,description:list.description,films:(list.film_ids||[]).slice(0,4).map(resolve).filter(Boolean),count:list.film_ids?.length||0,stats:[]}:null;}case'rewatch':{const sessions=(item.session_refs||[]).map(ref=>entities.sessions?.[ref]).filter(Boolean),film=resolve(sessions[0]?.film_id);return film?{type:'rewatch',film,sessions:sessions.map((row,index)=>({date:row.date,rating:row.rating,index:index+1})),stats:[]}:null;}case'phrase':return {type:'phrase',phrase:item.phrase||item.display_text||'',stats:item.values||[]};case'stat':return {type:'stat',stats:item.values||[]};default:return {type:'custom_attachment',title:item.title||item.type,label:item.display_text||'',values:item.values||[],films:(item.film_ids||[]).map(resolve).filter(Boolean)};}};
const stats=archive=>[{label:'Arquivos',value:archive.archive?.file_count||0},{label:'Reviews',value:archive.archive?.reviews||0},{label:'Linhas',value:archive.archive?.row_count||0}];
export function materializeFreeform({archive,judgment,locale='pt-BR',diagnostics={}}){
 const pt=locale==='pt-BR',events=[],beats=[],opening=judgment.opening||{},row=firstObject(archive,'profile.csv'),profile={handle:row.Username||'',name:row.Name||row.Username||''},favorites=topFour(archive),games=[...judgment.games],resolve=id=>filmObject(archive.entities?.films?.[id]);let gameIndex=0;
 for(const line of opening.greeting||[pt?'Certo.':'Right.'])events.push(typing('medium'),message(line));if(favorites.length){events.push(typing('long'),message(opening.archetype_lead,{cue:'top_four_reveal'}),message(opening.archetype_phrase,{role:'archetype_phrase'}));for(const line of opening.archetype_after||[])events.push(pause(),message(line));events.push(message(opening.username_line));}const taste=opening.taste_bit||{};if(taste.lead)events.push(typing(),message(taste.lead));if(taste.strike)events.push({type:'strike',text:clean(taste.strike)});if(taste.correction)events.push({type:'correction',original:clean(taste.strike),replacement:clean(taste.correction)});if(taste.tail)events.push(message(taste.tail));if(opening.judge_claim)events.push(message(opening.judge_claim));for(const line of opening.transition||[])events.push(typing(),message(line));events.push({type:'profile_stats',stats:stats(archive)});
 const addGame=game=>{const copy=game.copy||{},films=game.film_ids.map(resolve).filter(Boolean);events.push(typing(),{type:'game_intro',game_id:game.id,segments:segments(copy.intro)},{type:game.type==='forced_triage'?'game_forced_triage':game.type==='blind_rank'?'game_blind_rank':'game_defend_take',game_id:game.id,films,difficulty:game.difficulty||'hard',copy});};
 for(const [index,moment] of judgment.moments.entries()){const start=events.length;events.push(pause('medium'));if(moment.label)events.push({type:'moment_label',label:moment.label});for(const item of moment.attachments){const event=attachmentEvent(item,archive);if(event)events.push(event,pause('long'));}for(const line of moment.lines)events.push(typing(),message(line));beats.push({beat_id:moment.id,moment_id:moment.id,moment_type:moment.type,origin:'freeform',finding_ids:moment.evidence_refs,render_strategy:'ai',source:'freeform_judge',status:moment.lines.length?'written':'silent',lines:moment.lines.flatMap(segments),event_count:events.length-start});if(games[gameIndex]&&(index===Math.min(2,judgment.moments.length-1)||(gameIndex===1&&index===Math.max(4,judgment.moments.length-2))))addGame(games[gameIndex++]);}
 while(gameIndex<games.length)addGame(games[gameIndex++]);for(const line of judgment.closer)events.push(typing('medium'),message(line,{role:'closer'}));const summary=pt?`Modo experimental livre. O conteúdo completo dos ${archive.archive.file_count} arquivos foi enviado ao modelo sem pauta pré-selecionada.`:`Experimental freeform mode. All ${archive.archive.file_count} files were sent without preselected topics.`;
 return {version:'presentation-v2',template:'web_opening_v2',pipeline_mode:'freeform',locale,profile:{name:profile.name,handle:profile.handle,display_name:profile.name},stats:stats(archive),opening:{top_four:favorites,archetype_text:clean(opening.archetype_phrase),top_four_archetype:{requested:favorites.length===4,phrase:clean(opening.archetype_phrase),valid:favorites.length===4&&Boolean(opening.archetype_phrase)}},ending:judgment.ending,profile_review:judgment.profile_review,explainability:{mode:'freeform',summary,files_processed:archive.archive.file_count,evidence:judgment.moments.map(moment=>({moment:moment.id,evidence_refs:moment.evidence_refs})),models:{freeform_judge:{served_model:judgment._model,status:'complete',context_chars:judgment._request_chars}},archive:diagnostics},render:{ai_generation:'complete',model:'gemini',served_model:judgment._model,model_quality:/lite/i.test(judgment._model)?'fallback_lite':'primary',runtime:'cloudflare-pages'},ai:{origin:'api',attempts:judgment._attempts,warnings:judgment.invalid,calls:judgment._main_calls+(judgment._repair_calls||0)},generation_meta:{pipeline:'freeform',freeform_judge:{model:judgment._model,main_calls:judgment._main_calls,repair_calls:judgment._repair_calls||0}},beats,events};
}
