import {archiveRefs} from './archive-json.js';
const clean=value=>String(value||'').replace(/\s+/g,' ').trim(),refsOf=value=>(Array.isArray(value)?value:[]).map(clean).filter(Boolean),linesOf=value=>(Array.isArray(value)?value:[]).map(clean).filter(Boolean).slice(0,5);
const ATTACHMENTS=new Set(['film','film_pair','film_group','review_quote','tag','list','phrase','stat','rewatch','relationship','custom']);
const profileData=archive=>{const file=(archive.files||[]).find(row=>row.path.toLowerCase()==='profile.csv'),headers=file?.headers||[],row=file?.rows?.[1]?.cells||[];return Object.fromEntries(headers.map((key,index)=>[key,row[index]??'']));};
export function validArchetype(value,{handle='',titles=[]}={}){const phrase=clean(value),words=phrase.split(/\s+/).filter(Boolean),lower=phrase.toLowerCase();return Boolean(phrase)&&words.length>=3&&words.length<=12&&phrase.length<=100&&(!handle||!lower.includes(clean(handle).toLowerCase()))&&titles.filter(title=>title&&lower.includes(clean(title).toLowerCase())).length<3&&!/^(cinéfilo|cinefilo|amante de cinema|film bro)$/i.test(phrase);}
function attachmentValid(row,entities){if(!row||!ATTACHMENTS.has(row.type))return false;const {films={},reviews={},lists={},tags={},sessions={}}=entities;if(row.type==='film')return Boolean(films[row.film_id]);if(['film_pair','film_group'].includes(row.type)){const ids=Array.isArray(row.film_ids)?row.film_ids:[];return ids.length>=(row.type==='film_pair'?2:1)&&ids.every(id=>films[id]);}if(row.type==='review_quote')return Boolean(reviews[row.review_ref]);if(row.type==='list')return Boolean(lists[row.list_id]||row.list_ref);if(row.type==='tag')return Boolean(tags[row.tag_id]||clean(row.tag));if(row.type==='rewatch')return (row.session_refs||[]).length>0&&(row.session_refs||[]).every(ref=>sessions[ref]);return true;}
export function validateFreeformResponse(payload,archive){
  const registry=archiveRefs(archive),entities=archive.entities||{films:{},reviews:{},sessions:{},lists:{},tags:{}},invalid=[],validRefs=refs=>refs.length>0&&refs.every(ref=>registry.has(ref)),moments=[];
  for(const [index,row] of (Array.isArray(payload?.moments)?payload.moments:[]).slice(0,20).entries()){const evidence_refs=refsOf(row?.evidence_refs),all=Array.isArray(row?.attachments)?row.attachments:[],attachments=all.filter(item=>attachmentValid(item,entities));if(!row||!validRefs(evidence_refs)||attachments.length!==all.length){invalid.push({kind:'moment',index,id:row?.id||null,invalid_refs:evidence_refs.filter(ref=>!registry.has(ref)),invalid_attachments:all.filter(item=>!attachmentValid(item,entities))});continue;}moments.push({id:clean(row.id)||`moment_${String(index+1).padStart(2,'0')}`,type:clean(row.type)||'custom',label:clean(row.label).slice(0,60),attachments,lines:linesOf(row.lines),evidence_refs});}
  const games=[];for(const [index,row] of (Array.isArray(payload?.games)?payload.games:[]).slice(0,2).entries()){const evidence_refs=refsOf(row?.evidence_refs),film_ids=(Array.isArray(row?.film_ids)?row.film_ids:[]).slice(0,3),copy=row?.copy||{},roles=Array.isArray(copy.roles)?copy.roles:[],hints=Array.isArray(copy.reaction_hints)?copy.reaction_hints:[],typeValid=['forced_triage','blind_rank','defend_your_take'].includes(row?.type),filmsValid=film_ids.length===3&&new Set(film_ids).size===3&&film_ids.every(id=>entities.films?.[id]),copyValid=Boolean(clean(copy.intro))&&(row?.type!=='forced_triage'||(roles.length===3&&new Set(roles.map(role=>role.id)).size===3&&roles.every(role=>clean(role.label)&&Number.isFinite(Number(role.rank)))&&hints.length>0));if(!validRefs(evidence_refs)||!typeValid||!filmsValid||!copyValid){invalid.push({kind:'game',index,id:row?.id||null,reason:'invalid game structure or unresolved film'});continue;}games.push({...row,id:clean(row.id)||`game_${index+1}`,film_ids,evidence_refs,copy});}
  if(games.length===2&&clean(games[0].copy.intro).toLowerCase()===clean(games[1].copy.intro).toLowerCase()){invalid.push({kind:'game',index:1,id:games[1].id,reason:'duplicate game intro'});games.pop();}
  const info=profileData(archive),favoriteRefs=String(info['Favorite Films']||'').split(',').map(v=>v.trim().replace(/\/$/,'')).filter(Boolean).slice(0,4),favoriteTitles=favoriteRefs.map(ref=>Object.values(entities.films||{}).find(f=>String(f.uri||'').replace(/\/$/,'')===ref)?.title||ref),opening=payload?.opening&&typeof payload.opening==='object'?payload.opening:{},taste=opening.taste_bit||{},openingComplete=favoriteRefs.length!==4||((opening.greeting||[]).length>0&&clean(opening.archetype_lead)&&validArchetype(opening.archetype_phrase,{handle:info.Username,titles:favoriteTitles})&&(opening.archetype_after||[]).length>0&&clean(opening.username_line)&&clean(taste.lead)&&clean(taste.strike)&&clean(taste.correction)&&clean(taste.tail)&&clean(opening.judge_claim)&&(opening.transition||[]).length>0);if(!openingComplete)invalid.push({kind:'opening',reason:'incomplete or invalid Top Four opening'});
  const profileRefs=refsOf(payload?.profile_review?.evidence_refs),profile_review=clean(payload?.profile_review?.text)&&validRefs(profileRefs)?{text:clean(payload.profile_review.text),evidence_refs:profileRefs}:null;if(payload?.profile_review&&!profile_review)invalid.push({kind:'profile_review'});
  return {opening,moments,games,closer:linesOf(payload?.closer),ending:{title:clean(payload?.ending?.title).split(/\s+/).slice(0,6).join(' ')},profile_review,invalid,valid:openingComplete&&moments.length>0&&Boolean(profile_review)};
}
