#!/usr/bin/env python3
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANALYST = ROOT / "prompts" / "analyst.txt"
WRITER = ROOT / "prompts" / "writer.txt"
OUTPUT = ROOT / "functions" / "_lib" / "generated-prompts.js"

def render() -> str:
    analyst = ANALYST.read_text(encoding="utf-8")
    writer = WRITER.read_text(encoding="utf-8")
    return (
        "// AUTO-GENERATED by scripts/sync-prompts.py. Do not edit by hand.\n"
        f"export const ANALYST_PROMPT = {json.dumps(analyst, ensure_ascii=False)};\n"
        f"export const WRITER_PROMPT = {json.dumps(writer, ensure_ascii=False)};\n"
    )

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != expected:
            print("generated-prompts.js is out of sync. Run: python scripts/sync-prompts.py")
            return 1
        print("prompt sync OK")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
