import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "judge-mode.json"
TARGET = ROOT / "functions" / "_lib" / "generated-mode.js"
ALLOWED = {"curated", "freeform"}


def rendered() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    if data.get("version") != 1 or data.get("pipeline") not in ALLOWED:
        raise SystemExit('judge-mode.json must have version 1 and pipeline "curated" or "freeform"')
    return ("// Generated by scripts/sync-mode.py. Do not edit directly.\n"
            f"export const JUDGE_PIPELINE_MODE = {json.dumps(data['pipeline'])};\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = rendered()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("generated-mode.js is out of sync; run python scripts/sync-mode.py")
        return
    TARGET.write_text(expected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
