import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "functions" / "_lib" / "generated-prompts.js"

def rendered():
    analyst = (ROOT / "prompts" / "analyst.txt").read_text(encoding="utf-8")
    writer = (ROOT / "prompts" / "writer.txt").read_text(encoding="utf-8")
    return ("// Generated by scripts/sync-prompts.py. Do not edit directly.\n"
            f"export const ANALYST_PROMPT = {json.dumps(analyst, ensure_ascii=False)};\n"
            f"export const WRITER_PROMPT = {json.dumps(writer, ensure_ascii=False)};\n")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = rendered()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("generated-prompts.js is out of sync; run python scripts/sync-prompts.py")
        return
    TARGET.write_text(expected, encoding="utf-8", newline="\n")

if __name__ == "__main__":
    main()
